

Development:
  DEBUG_FLAG: 0
  b: 5

PreProcessing:
  c: 2
  d: 5

SbdCore:
  PATH_RAW_RESULTS: "./"
  PREFIX_RAW_RESULTS: "results_raw_"
  POSTFIX_RAW_RESULTS: "csv"

  PATH_FINAL_RESULTS: "./"
  PREFIX_FINAL_RESULTS: "results_"
  POSTFIX_FINAL_RESULTS: "csv"

  PATH_VIDEOS: "/caa/Projects02/vhh/private/dzafirova/sbd_efilms_db_20190621/videos_converted/"
  THRESHOLD: 0.8
  BACKBONE_CNN: "squeeze"
  SIMILARITY_METRIC: "cosine"

PostProcessing:
  c: 2
  d: 5

Visualization:
  c: 2
  d: 5