

Development:
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate

PreProcessing:
  RESIZE_DIM: 128, 128      # resize dimension -> height, width
  CONVERT2GRAY: 0           # 0 or 1   --> not working yet
  CROP: 1                   # 0 or 1
  DOWNSCALE: 1              # 0 or 1
  HISTOGRAM_EQU: 'none'     # "clahe" or "classic" or "none"

SbdCore:
  CANDIDATE_SELECTION: 0    # 1 ... activate 0 ... deactivate

  SAVE_RAW_RESULTS: 1       # 1 ... yes 0 ... no
  PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp01_none/efilms/results_raw/"
  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp02_clahe/efilms/results_raw/"
  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp03_classic/efilms/results_raw/"
  PREFIX_RAW_RESULTS: "results_raw_"
  POSTFIX_RAW_RESULTS: "csv"

  SAVE_FINAL_RESULTS: 1     # 1 ... yes 0 ... no
  PATH_FINAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp01_none/efilms/results_final/"
  #PATH_FINAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp02_clahe/efilms/results_final/"
  #PATH_FINAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp03_classic/efilms/results_final/"
  PREFIX_FINAL_RESULTS: "results_"
  POSTFIX_FINAL_RESULTS: "csv"

  PATH_VIDEOS: "/caa/Projects02/vhh/private/dzafirova_nobackup/sbd_efilms_db_20190621/videos_converted/"
  THRESHOLD: 0.8
  BACKBONE_CNN: "vgg16"    # vgg16 OR squeezenet
  SIMILARITY_METRIC: "cosine"    # euclidean OR cosine

CandidateSelection:
  PATH_PRETRAINED_MODEL: "/caa/Homes01/dhelm/working/pycharm_sbd_clipshot/ClipShots_basline/pretrained/Alexnet-final.pth"

PostProcessing:
  c: 2
  d: 5

Visualization:
  c: 2
  d: 5

Evaluation:
  SAVE_EVAL_RESULTS: 1
  PATH_GT_ANNOTATIONS: "/caa/Projects02/vhh/private/database_nobackup/VHH_datasets/annotations/ShotBoundaryDetection/efilms/shotBoundaries_annotations_v8_20190523.csv"
  PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp01_none/efilms/results_raw/"
  PATH_EVAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp01_none/efilms/Evaluation/"

  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp02_clahe/efilms/results_raw/"
  #PATH_EVAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp02_clahe/efilms/Evaluation/"

  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp03_classic/efilms/results_raw/"
  #PATH_EVAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/vgg/Exp03_classic/efilms/Evaluation/"


