

Development:
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate

PreProcessing:
  RESIZE_DIM: 128, 128      # resize dimension -> height, width
  CONVERT2GRAY: 0           # 0 or 1   --> not working yet
  CROP: 1                   # 0 or 1
  DOWNSCALE: 1              # 0 or 1
  HISTOGRAM_EQU: 'classic'     # "clahe" or "classic" or "none"

SbdCore:
  CANDIDATE_SELECTION: 0    # 1 ... activate 0 ... deactivate

  SAVE_RAW_RESULTS: 1       # 1 ... yes 0 ... no
  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp09_none/holocaust/results_raw/"
  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp10_clahe/holocaust/results_raw/"
  PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp11_classic/holocaust/results_raw/"
  PREFIX_RAW_RESULTS: "results_raw_"
  POSTFIX_RAW_RESULTS: "npy"

  SAVE_FINAL_RESULTS: 1     # 1 ... yes 0 ... no
  #PATH_FINAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp09_none/holocaust/results_final/"
  #PATH_FINAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp10_clahe/holocaust/results_final/"
  PATH_FINAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp11_classic/holocaust/results_final/"
  PREFIX_FINAL_RESULTS: "results_"
  POSTFIX_FINAL_RESULTS: "csv"

  PATH_VIDEOS: "/caa/Projects02/vhh/private/database_nobackup/VHH_datasets/videos_holocaust/test/"
  THRESHOLD_MODE: 'fixed'    # adaptive OR fixed
  THRESHOLD: 0.5
  WINDOW_SIZE: 10               # only for adaptive mode
  BACKBONE_CNN: "squeezenet"    # vgg16 OR squeezenet
  SIMILARITY_METRIC: "cosine"    # euclidean OR cosine

CandidateSelection:
  PATH_PRETRAINED_MODEL: "/caa/Homes01/dhelm/working/pycharm_sbd_clipshot/ClipShots_basline/pretrained/Alexnet-final.pth"

PostProcessing:
  c: 2
  d: 5

Visualization:
  c: 2
  d: 5

Evaluation:
  SAVE_EVAL_RESULTS: 1
  PATH_GT_ANNOTATIONS: "/caa/Projects02/vhh/private/database_nobackup/VHH_datasets/annotations/ShotBoundaryDetection/holocaust/shotBoundaries_annotations_v8_20190523.csv"
  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp09_none/holocaust/results_raw/"
  #PATH_EVAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp09_none/holocaust/Evaluation/"

  #PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp10_clahe/holocaust/results_raw/"
  #PATH_EVAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp10_clahe/holocaust/Evaluation/"

  PATH_RAW_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp11_classic/holocaust/results_raw/"
  PATH_EVAL_RESULTS: "/caa/Projects02/vhh/private/Results/ShotBoundaryDetection/20191212_vhh_sbd/squeezenet/Exp11_classic/holocaust/Evaluation/"


